import { useMemo, useState } from "react";
import {
  Activity, AlertCircle, ArrowDownLeft, ArrowUpLeft, Bell, CalendarDays, Check,
  CheckCircle2, ChevronDown, CircleDashed, ClipboardList, Download, Edit3, FileText,
  Filter, Flag, LayoutDashboard, Menu, MoreHorizontal, Plus, Search, Settings2,
  Target, Trash2, TrendingUp, UserRound, Users, X, Zap
} from "lucide-react";
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart,
  ResponsiveContainer, Tooltip, XAxis, YAxis
} from "recharts";
import { toast } from "sonner";
import { Goal, GoalStatus, departments, initialGoals, statusData, weeklyReportSchema, weeklyTrend } from "../../../shared/dashboard";

const statusStyles: Record<GoalStatus, string> = {
  "انجام شده": "bg-emerald-50 text-emerald-700 border-emerald-100",
  "در حال انجام": "bg-blue-50 text-blue-700 border-blue-100",
  "نیاز به اقدام": "bg-amber-50 text-amber-700 border-amber-100",
  "انجام نشده": "bg-slate-100 text-slate-600 border-slate-200",
};

function StatusBadge({ status }: { status: GoalStatus }) {
  const Icon = status === "انجام شده" ? CheckCircle2 : status === "نیاز به اقدام" ? AlertCircle : status === "در حال انجام" ? Activity : CircleDashed;
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-semibold whitespace-nowrap ${statusStyles[status]}`}><Icon size={13} />{status}</span>;
}

function MetricCard({ label, value, change, icon: Icon, tone = "blue" }: { label: string; value: string; change: string; icon: typeof Target; tone?: string }) {
  const tones: Record<string, string> = { blue: "bg-blue-50 text-blue-600", green: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600", navy: "bg-slate-100 text-slate-700", red: "bg-red-50 text-red-600" };
  return <div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-[0_4px_20px_rgba(15,23,42,0.035)] transition hover:-translate-y-0.5 hover:shadow-lg">
    <div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-extrabold tracking-tight text-slate-900">{value}</p></div><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${tones[tone]}`}><Icon size={20} /></div></div>
    <div className="mt-4 flex items-center gap-1.5 text-xs font-medium text-emerald-600"><ArrowUpLeft size={14} />{change}<span className="font-normal text-slate-400">نسبت به هفته قبل</span></div>
  </div>;
}

export default function Home() {
  const [section, setSection] = useState("dashboard");
  const [goals, setGoals] = useState(initialGoals);
  const [query, setQuery] = useState("");
  const [unit, setUnit] = useState("همه واحدها");
  const [selectedGoal, setSelectedGoal] = useState<Goal | null>(null);
  const [showReport, setShowReport] = useState(false);
  const [showGoalForm, setShowGoalForm] = useState(false);
  const [editingGoal, setEditingGoal] = useState<Goal | null>(null);
  const [mobileNav, setMobileNav] = useState(false);
  const [reportText, setReportText] = useState("");
  const [reportProgress, setReportProgress] = useState("65");

  const filteredGoals = useMemo(() => goals.filter((g: Goal) => (unit === "همه واحدها" || g.unit === unit) && g.title.includes(query)), [goals, query, unit]);
  const nav = [
    { id: "dashboard", label: "داشبورد", icon: LayoutDashboard }, { id: "goals", label: "مدیریت اهداف", icon: Target },
    { id: "reports", label: "گزارش هفتگی", icon: ClipboardList }, { id: "analytics", label: "تحلیل عملکرد", icon: TrendingUp },
    { id: "executive", label: "گزارش مدیریتی", icon: FileText }, { id: "compare", label: "مقایسه هفتگی", icon: Activity },
  ];
  const title = nav.find(n => n.id === section)?.label || "داشبورد";

  function deleteGoal(id: number) { setGoals((g: Goal[]) => g.filter((item: Goal) => item.id !== id)); toast.success("هدف با موفقیت حذف شد"); }
  function submitReport(e: React.FormEvent) { e.preventDefault(); const result = weeklyReportSchema.safeParse({ text: reportText, progress: reportProgress }); if (!result.success) { toast.error(result.error.issues[0]?.message || "اطلاعات گزارش معتبر نیست"); return; } setShowReport(false); setReportText(""); toast.success("گزارش هفتگی ثبت شد"); }
  function exportReport() { toast.success("گزارش برای دریافت آماده شد"); }

  return <div dir="rtl" className="min-h-screen bg-[#f6f8fb] text-slate-900">
    <aside className={`fixed inset-y-0 right-0 z-40 flex w-[264px] flex-col bg-[#0f1d35] text-white transition-transform lg:translate-x-0 ${mobileNav ? "translate-x-0" : "translate-x-full"}`}>
      <div className="flex h-[88px] items-center gap-3 border-b border-white/10 px-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500 shadow-lg shadow-blue-500/25"><Activity size={22} /></div><div><p className="text-[15px] font-bold tracking-tight">دیدبان عملکرد</p><p className="mt-0.5 text-[10px] text-slate-400">سامانه مدیریت اهداف</p></div><button className="mr-auto lg:hidden" onClick={() => setMobileNav(false)}><X size={19} /></button></div>
      <div className="px-4 pt-7"><p className="mb-3 px-3 text-[10px] font-bold tracking-[0.18em] text-slate-500">منوی اصلی</p>{nav.map(item => <button key={item.id} onClick={() => { setSection(item.id); setMobileNav(false); }} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm transition ${section === item.id ? "bg-blue-500 text-white shadow-lg shadow-blue-900/30" : "text-slate-300 hover:bg-white/5 hover:text-white"}`}><item.icon size={18} /><span>{item.label}</span>{item.id === "reports" && <span className="mr-auto flex h-5 min-w-5 items-center justify-center rounded-full bg-amber-400 px-1 text-[10px] font-bold text-slate-900">۳</span>}</button>)}</div>
      <div className="mt-auto border-t border-white/10 p-4"><div className="mb-4 flex items-center gap-3 rounded-xl bg-white/5 p-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-400 text-sm font-bold">م</div><div className="min-w-0"><p className="truncate text-xs font-semibold">مدیر سیستم</p><p className="truncate text-[10px] text-slate-400">admin@organization.ir</p></div><MoreHorizontal className="mr-auto text-slate-500" size={16} /></div><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-xs text-slate-400 hover:bg-white/5 hover:text-white"><Settings2 size={16} />تنظیمات سامانه</button></div>
    </aside>
    {mobileNav && <div className="fixed inset-0 z-30 bg-slate-950/50 lg:hidden" onClick={() => setMobileNav(false)} />}
    <main className="lg:mr-[264px]">
      <header className="sticky top-0 z-20 flex h-[88px] items-center justify-between border-b border-slate-200/80 bg-white/90 px-5 backdrop-blur-xl md:px-9"><div className="flex items-center gap-3"><button className="rounded-lg p-2 hover:bg-slate-100 lg:hidden" onClick={() => setMobileNav(true)}><Menu size={21} /></button><div><p className="text-xs text-slate-400">شنبه، ۳۱ مرداد ۱۴۰۵</p><h1 className="mt-1 text-xl font-extrabold tracking-tight text-slate-900">{title}</h1></div></div><div className="flex items-center gap-2 md:gap-4"><button onClick={() => toast("۳ اعلان جدید برای بررسی دارید")} className="relative rounded-xl border border-slate-200 p-2.5 text-slate-500 hover:bg-slate-50"><Bell size={18} /><span className="absolute -right-1 -top-1 h-2.5 w-2.5 rounded-full border-2 border-white bg-amber-400" /></button><div className="hidden h-8 w-px bg-slate-200 md:block" /><div className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-100 text-xs font-bold text-blue-700">م</div><div className="hidden text-right md:block"><p className="text-xs font-bold">مدیر سیستم</p><p className="text-[10px] text-slate-400">مدیریت ارشد</p></div><ChevronDown size={14} className="text-slate-400" /></div></div></header>
      <div className="mx-auto max-w-[1440px] p-5 md:p-9">
        {section === "dashboard" && <DashboardView filteredGoals={filteredGoals} query={query} setQuery={setQuery} unit={unit} setUnit={setUnit} setSelectedGoal={setSelectedGoal} deleteGoal={deleteGoal} setShowReport={setShowReport} exportReport={exportReport} />}
        {section === "goals" && <GoalsView goals={filteredGoals} query={query} setQuery={setQuery} unit={unit} setUnit={setUnit} setSelectedGoal={setSelectedGoal} deleteGoal={deleteGoal} setShowGoalForm={setShowGoalForm} setShowReport={setShowReport} />}
        {section === "reports" && <ReportsView setShowReport={setShowReport} />}
        {section === "analytics" && <AnalyticsView />}
        {section === "executive" && <ExecutiveView exportReport={exportReport} />}
        {section === "compare" && <CompareView />}
      </div>
    </main>
    {selectedGoal && <GoalDetail goal={selectedGoal} close={() => setSelectedGoal(null)} />}
    {showReport && <ReportModal text={reportText} setText={setReportText} progress={reportProgress} setProgress={setReportProgress} close={() => setShowReport(false)} submit={submitReport} />}
    {showGoalForm && <GoalModal close={() => setShowGoalForm(false)} add={(g: Omit<Goal, "id" | "updated">) => { setGoals((prev: Goal[]) => [{ ...g, id: Date.now(), updated: "همین حالا" }, ...prev]); setShowGoalForm(false); toast.success("هدف جدید اضافه شد"); }} />}
  </div>;
}

function DashboardView({ filteredGoals, query, setQuery, unit, setUnit, setSelectedGoal, deleteGoal, setShowReport, exportReport }: any) { return <>
  <div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-sm font-semibold text-blue-600">گزارش هفتگی سازمان</p><h2 className="text-2xl font-extrabold tracking-tight text-slate-900 md:text-3xl">سلام، روز بخیر</h2><p className="mt-2 text-sm text-slate-500">تصویر کلی عملکرد تیم را در هفته جاری بررسی کنید.</p></div><div className="flex flex-wrap gap-2"><button className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-semibold text-slate-600"><CalendarDays size={15} />۲۴ تا ۳۰ مرداد ۱۴۰۵<ChevronDown size={14} /></button><button onClick={exportReport} className="flex items-center gap-2 rounded-xl bg-[#17325c] px-4 py-2.5 text-xs font-semibold text-white shadow-lg shadow-slate-900/10 hover:bg-[#214579]"><Download size={15} />خروجی گزارش</button></div></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard label="میانگین پیشرفت کل" value="۶۵٪" change="+۸٪" icon={TrendingUp} tone="blue" /><MetricCard label="تعداد کل اهداف" value="۲۰" change="+۲" icon={Target} tone="navy" /><MetricCard label="اهداف تکمیل‌شده" value="۷" change="+۱" icon={CheckCircle2} tone="green" /><MetricCard label="در حال انجام" value="۸" change="+۳" icon={Activity} tone="blue" /><MetricCard label="نیازمند اقدام" value="۳" change="-۱" icon={AlertCircle} tone="amber" /></div>
  <div className="mt-6 grid gap-5 xl:grid-cols-[1.55fr_1fr]"><div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm md:p-6"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-bold">روند پیشرفت هفتگی</h3><p className="mt-1 text-xs text-slate-400">میانگین تحقق اهداف در ۸ هفته اخیر</p></div><span className="rounded-lg bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-600">+۴۶٪ رشد</span></div><div className="h-[250px] w-full"><ResponsiveContainer><AreaChart data={weeklyTrend} margin={{ top: 10, right: 0, left: -20, bottom: 0 }}><defs><linearGradient id="trendFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity={0.22} /><stop offset="100%" stopColor="#2563eb" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eef2f7" /><XAxis dataKey="week" tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} tickFormatter={(v) => `${v}%`} tick={{ fontSize: 10, fill: "#94a3b8" }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ borderRadius: 12, border: "1px solid #e2e8f0", fontFamily: "Vazirmatn" }} formatter={(v) => [`${v}%`, "پیشرفت"]} /><Area type="monotone" dataKey="value" stroke="#2563eb" strokeWidth={3} fill="url(#trendFill)" dot={{ r: 4, fill: "#fff", stroke: "#2563eb", strokeWidth: 2 }} activeDot={{ r: 6 }} /></AreaChart></ResponsiveContainer></div></div><div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm md:p-6"><div className="mb-2"><h3 className="font-bold">وضعیت اهداف</h3><p className="mt-1 text-xs text-slate-400">توزیع وضعیت اهداف فعال</p></div><div className="relative h-[190px]"><ResponsiveContainer><PieChart><Pie data={statusData} dataKey="value" nameKey="name" innerRadius={57} outerRadius={82} paddingAngle={4} stroke="none">{statusData.map((s: { name: string; value: number; color: string }) => <Cell key={s.name} fill={s.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="text-3xl font-extrabold">۲۰</span><span className="text-[11px] text-slate-400">هدف فعال</span></div></div><div className="grid grid-cols-2 gap-y-2 px-2">{statusData.map((s: { name: string; value: number; color: string }) => <div key={s.name} className="flex items-center gap-2 text-xs text-slate-500"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: s.color }} />{s.name}<b className="mr-auto text-slate-700">{s.value}</b></div>)}</div></div></div>
  <div className="mt-5 rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm md:p-6"><div className="mb-5 flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><h3 className="font-bold">جزئیات اهداف</h3><p className="mt-1 text-xs text-slate-400">آخرین وضعیت اهداف کلیدی سازمان</p></div><div className="flex flex-wrap gap-2"><div className="relative"><Search size={15} className="absolute right-3 top-2.5 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="جستجوی هدف..." className="h-9 w-44 rounded-lg border border-slate-200 bg-slate-50 pr-9 pl-3 text-xs outline-none focus:border-blue-400" /></div><select value={unit} onChange={e => setUnit(e.target.value)} className="h-9 rounded-lg border border-slate-200 bg-slate-50 px-3 text-xs text-slate-600 outline-none"><option>همه واحدها</option><option>اجرایی</option><option>آموزش</option><option>نظارت</option><option>مطالعات</option><option>پشتیبانی</option></select><button className="flex h-9 items-center gap-1.5 rounded-lg border border-slate-200 px-3 text-xs text-slate-500"><Filter size={14} />فیلتر</button></div></div><GoalTable goals={filteredGoals} setSelectedGoal={setSelectedGoal} deleteGoal={deleteGoal} setShowReport={setShowReport} /></div>
  <div className="mt-5 grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-bold">مقایسه عملکرد واحدها</h3><p className="mt-1 text-xs text-slate-400">برنامه‌ریزی شده در برابر پیشرفت واقعی</p></div><button className="text-xs font-semibold text-blue-600" onClick={() => toast("جزئیات عملکرد واحدها نمایش داده شد")}>مشاهده جزئیات</button></div><div className="h-[245px]"><ResponsiveContainer><BarChart data={departments} margin={{ left: -20, right: 5 }}><CartesianGrid vertical={false} stroke="#eef2f7" /><XAxis dataKey="name" tick={{ fontSize: 11, fill: "#64748b" }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} tickFormatter={v => `${v}%`} tick={{ fontSize: 10, fill: "#94a3b8" }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ borderRadius: 12, border: "1px solid #e2e8f0" }} formatter={(v, n) => [`${v}%`, n === "actual" ? "واقعی" : "برنامه"]} /><Bar dataKey="planned" fill="#dbeafe" radius={[5, 5, 0, 0]} barSize={13} /><Bar dataKey="actual" fill="#2563eb" radius={[5, 5, 0, 0]} barSize={13} /></BarChart></ResponsiveContainer></div></div><div className="rounded-2xl border border-blue-100 bg-gradient-to-br from-[#eff6ff] to-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><span className="inline-flex items-center gap-1.5 rounded-full bg-blue-100 px-2.5 py-1 text-[10px] font-bold text-blue-700"><Zap size={12} />اقدام پیشنهادی</span><h3 className="mt-3 text-lg font-extrabold text-slate-900">۳ هدف نیازمند توجه شماست</h3><p className="mt-2 max-w-md text-xs leading-6 text-slate-500">با ثبت گزارش هفتگی و تعیین اقدام بعدی، روند تحقق اهداف را به مسیر برنامه‌ریزی‌شده برگردانید.</p></div><div className="hidden h-12 w-12 items-center justify-center rounded-2xl bg-white text-blue-600 shadow-sm sm:flex"><Flag size={22} /></div></div><button onClick={() => setShowReport(true)} className="mt-5 flex items-center gap-2 rounded-xl bg-[#17325c] px-4 py-2.5 text-xs font-bold text-white hover:bg-[#214579]">ثبت گزارش هفتگی<ArrowDownLeft size={15} /></button></div></div>
</> }

function GoalTable({ goals, setSelectedGoal, deleteGoal, setShowReport }: any) { return <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-right"><thead><tr className="border-b border-slate-100 text-[11px] font-semibold text-slate-400"><th className="pb-3 pr-2">هدف / واحد</th><th className="pb-3">مسئول</th><th className="pb-3">وزن</th><th className="pb-3">برنامه</th><th className="pb-3">پیشرفت واقعی</th><th className="pb-3">وضعیت</th><th className="pb-3">عملیات</th></tr></thead><tbody>{goals.map((g: Goal) => <tr key={g.id} className="border-b border-slate-50 last:border-0 hover:bg-slate-50/60"><td className="py-4 pr-2"><button onClick={() => setSelectedGoal(g)} className="text-right"><p className="text-xs font-bold text-slate-800 hover:text-blue-600">{g.title}</p><p className="mt-1 text-[10px] text-slate-400">{g.unit}</p></button></td><td className="py-4 text-xs text-slate-600">{g.owner}</td><td className="py-4 text-xs font-semibold text-slate-600">{g.weight}٪</td><td className="py-4"><div className="flex items-center gap-2 text-xs text-slate-500"><div className="h-1.5 w-16 rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-300" style={{ width: `${g.plan}%` }} /></div>{g.plan}٪</div></td><td className="py-4"><div className="flex items-center gap-2 text-xs font-bold text-slate-700"><div className="h-1.5 w-16 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-500" style={{ width: `${g.actual}%` }} /></div>{g.actual}٪</div></td><td className="py-4"><StatusBadge status={g.status} /></td><td className="py-4"><details className="relative"><summary className="flex list-none items-center rounded-lg p-2 text-slate-400 hover:bg-slate-100"><MoreHorizontal size={16} /></summary><div className="absolute left-0 top-9 z-10 w-32 rounded-xl border border-slate-200 bg-white p-1 text-xs shadow-xl"><button className="block w-full rounded-lg px-3 py-2 text-right hover:bg-slate-50" onClick={() => setSelectedGoal(g)}>مشاهده</button><button className="block w-full rounded-lg px-3 py-2 text-right hover:bg-slate-50" onClick={() => toast.success("فرم ویرایش هدف آماده شد")}>ویرایش</button><button className="block w-full rounded-lg px-3 py-2 text-right hover:bg-slate-50" onClick={() => setShowReport?.(true)}>ثبت گزارش</button><button className="block w-full rounded-lg px-3 py-2 text-right text-red-600 hover:bg-red-50" onClick={() => deleteGoal(g.id)}>حذف</button></div></details></td></tr>)}</tbody></table>{goals.length === 0 && <div className="py-12 text-center text-sm text-slate-400">هدف موردنظر پیدا نشد.</div>}</div> }

function GoalsView({ goals, query, setQuery, unit, setUnit, setSelectedGoal, deleteGoal, setShowGoalForm, setShowReport }: any) { return <div><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-sm font-semibold text-blue-600">مرکز کنترل اهداف</p><h2 className="text-2xl font-extrabold">مدیریت اهداف</h2><p className="mt-2 text-sm text-slate-500">اهداف سازمان را ایجاد، پیگیری و به‌روزرسانی کنید.</p></div><button onClick={() => setShowGoalForm(true)} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-blue-600/20"><Plus size={17} />افزودن هدف جدید</button></div><div className="mb-5 flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4"><div className="relative"><Search size={16} className="absolute right-3 top-3 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="جستجو در اهداف" className="h-10 w-64 rounded-xl border border-slate-200 bg-slate-50 pr-10 pl-3 text-sm outline-none focus:border-blue-400" /></div><select value={unit} onChange={e => setUnit(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm text-slate-600 outline-none"><option>همه واحدها</option><option>اجرایی</option><option>آموزش</option><option>نظارت</option><option>مطالعات</option><option>پشتیبانی</option></select></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><GoalTable goals={goals} setSelectedGoal={setSelectedGoal} deleteGoal={deleteGoal} setShowReport={setShowReport} /></div></div> }

function ReportsView({ setShowReport }: any) { return <div><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-sm font-semibold text-blue-600">ثبت و پیگیری</p><h2 className="text-2xl font-extrabold">گزارش هفتگی</h2><p className="mt-2 text-sm text-slate-500">گزارش عملکرد هفته ۲۴ تا ۳۰ مرداد ۱۴۰۵</p></div><button onClick={() => setShowReport(true)} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white"><Plus size={17} />ثبت گزارش جدید</button></div><div className="grid gap-4 md:grid-cols-3"><MetricCard label="پیشرفت این هفته" value="۶۵٪" change="+۸٪" icon={TrendingUp} /><MetricCard label="گزارش‌های ثبت‌شده" value="۱۲" change="+۴" icon={FileText} tone="green" /><MetricCard label="اهداف دارای مانع" value="۳" change="-۱" icon={AlertCircle} tone="amber" /></div><div className="mt-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-bold">گزارش‌های اخیر</h3><div className="mt-5 space-y-4">{["گزارش پیشرفت دوره‌های آموزشی", "به‌روزرسانی داشبورد مدیریتی", "گزارش وضعیت زیرساخت"].map((x, i) => <div key={x} className="flex items-center gap-4 rounded-xl border border-slate-100 p-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><FileText size={18} /></div><div className="flex-1"><p className="text-sm font-bold">{x}</p><p className="mt-1 text-xs text-slate-400">ثبت‌شده توسط {i === 0 ? "سارا احمدی" : "مریم کریمی"} · {i + 1} روز پیش</p></div><CheckCircle2 className="text-emerald-500" size={18} /></div>)}</div></div></div> }

function AnalyticsView() { return <div><div className="mb-7"><p className="mb-2 text-sm font-semibold text-blue-600">تصمیم‌گیری داده‌محور</p><h2 className="text-2xl font-extrabold">تحلیل عملکرد</h2><p className="mt-2 text-sm text-slate-500">شاخص‌های عملکرد را با جزئیات بیشتری بررسی کنید.</p></div><div className="mb-5 flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-4"><select className="h-10 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"><option>۸ هفته اخیر</option><option>۶ ماه اخیر</option></select><select className="h-10 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"><option>همه واحدها</option><option>آموزش</option><option>اجرایی</option></select><select className="h-10 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"><option>همه وضعیت‌ها</option><option>انجام شده</option><option>نیاز به اقدام</option></select></div><div className="grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-bold">روند وزنی عملکرد</h3><div className="mt-5 h-[290px]"><ResponsiveContainer><LineChart data={weeklyTrend}><CartesianGrid vertical={false} stroke="#eef2f7" /><XAxis dataKey="week" tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tickFormatter={v => `${v}%`} axisLine={false} tickLine={false} /><Tooltip /><Line type="monotone" dataKey="value" stroke="#17325c" strokeWidth={3} dot={{ fill: "#fff", stroke: "#2563eb", strokeWidth: 2, r: 5 }} /></LineChart></ResponsiveContainer></div></div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="font-bold">عملکرد واحدها</h3><div className="mt-5 h-[290px]"><ResponsiveContainer><BarChart data={departments} layout="vertical" margin={{ left: 10, right: 10 }}><CartesianGrid horizontal={false} stroke="#eef2f7" /><XAxis type="number" domain={[0, 100]} hide /><YAxis type="category" dataKey="name" width={60} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="actual" fill="#2563eb" radius={[0, 6, 6, 0]} barSize={18} /></BarChart></ResponsiveContainer></div></div></div></div> }

function ExecutiveView({ exportReport }: any) { return <div><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-sm font-semibold text-blue-600">برای جلسه دوشنبه صبح</p><h2 className="text-2xl font-extrabold">گزارش مدیریتی</h2><p className="mt-2 text-sm text-slate-500">گزارش عملکرد هفتگی · ۲۴ تا ۳۰ مرداد ۱۴۰۵</p></div><button onClick={exportReport} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700"><Download size={16} />Export PDF</button></div><div className="rounded-2xl bg-[#17325c] p-6 text-white shadow-xl shadow-slate-900/10 md:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs text-blue-200">جمع‌بندی اجرایی هفته</p><p className="mt-3 text-5xl font-extrabold">۶۵٪</p><p className="mt-2 text-sm text-blue-100">پیشرفت کل اهداف سازمان <span className="mr-2 rounded-full bg-emerald-400/20 px-2 py-1 text-emerald-300">+۸٪</span></p></div><div className="grid grid-cols-3 gap-8 text-center"><div><p className="text-2xl font-bold">۷</p><p className="mt-1 text-[11px] text-blue-200">تکمیل‌شده</p></div><div><p className="text-2xl font-bold">۸</p><p className="mt-1 text-[11px] text-blue-200">در حال انجام</p></div><div><p className="text-2xl font-bold text-amber-300">۳</p><p className="mt-1 text-[11px] text-blue-200">نیازمند اقدام</p></div></div></div></div><div className="mt-5 grid gap-5 md:grid-cols-3"><SummaryCard title="مهم‌ترین دستاوردهای هفته" icon={CheckCircle2} color="green" items={["راه‌اندازی نسخه اول داشبورد مدیریتی", "تکمیل مستندات دانش سازمانی", "افزایش مشارکت در دوره‌های آموزشی"]} /><SummaryCard title="مهم‌ترین مشکلات" icon={AlertCircle} color="amber" items={["تاخیر در تدوین گزارش مطالعات بازار", "نیاز به تخصیص منابع برای آموزش", "کندی فرآیند تأیید ارزیابی"]} /><SummaryCard title="اقدامات ضروری هفته آینده" icon={Zap} color="blue" items={["جلسه پیگیری با واحد مطالعات", "ثبت برنامه جبرانی آموزش", "تعیین مالک اقدام‌های باز"]} /></div></div> }
function SummaryCard({ title, icon: Icon, color, items }: any) { const c: any = { green: "text-emerald-600 bg-emerald-50", amber: "text-amber-600 bg-amber-50", blue: "text-blue-600 bg-blue-50" }; return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><span className={`flex h-8 w-8 items-center justify-center rounded-lg ${c[color]}`}><Icon size={16} /></span><h3 className="text-sm font-bold">{title}</h3></div><ul className="mt-4 space-y-3">{items.map((x: string) => <li key={x} className="flex gap-2 text-xs leading-5 text-slate-600"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-slate-300" />{x}</li>)}</ul></div> }

function CompareView() { return <div><div className="mb-7"><p className="mb-2 text-sm font-semibold text-blue-600">تحلیل تغییرات</p><h2 className="text-2xl font-extrabold">مقایسه هفتگی</h2><p className="mt-2 text-sm text-slate-500">هفته جاری در برابر هفته قبل</p></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[{ l: "پیشرفت کل", a: "۶۵٪", b: "۵۷٪", c: "+۸٪", tone: "text-emerald-600" }, { l: "اهداف تکمیل‌شده", a: "۷", b: "۶", c: "+۱", tone: "text-emerald-600" }, { l: "اهداف نیازمند اقدام", a: "۳", b: "۴", c: "-۱", tone: "text-emerald-600" }, { l: "گزارش‌های ثبت‌شده", a: "۱۲", b: "۹", c: "+۳", tone: "text-blue-600" }].map(x => <div key={x.l} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{x.l}</p><div className="mt-4 flex items-end gap-3"><p className="text-3xl font-extrabold">{x.a}</p><p className="pb-1 text-xs text-slate-400">از {x.b}</p></div><p className={`mt-3 text-xs font-bold ${x.tone}`}>{x.c} تغییر نسبت به هفته قبل</p></div>)}</div><div className="mt-5 grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-emerald-100 bg-emerald-50/60 p-6"><p className="text-xs font-bold text-emerald-700">بیشترین بهبود</p><h3 className="mt-3 text-xl font-extrabold">واحد آموزش <span className="text-emerald-600">+۱۴٪</span></h3><p className="mt-2 text-sm text-slate-500">افزایش تکمیل دوره‌ها و ثبت منظم گزارش‌ها.</p></div><div className="rounded-2xl border border-amber-100 bg-amber-50/60 p-6"><p className="text-xs font-bold text-amber-700">بیشترین افت</p><h3 className="mt-3 text-xl font-extrabold">واحد نظارت <span className="text-amber-600">-۵٪</span></h3><p className="mt-2 text-sm text-slate-500">نیازمند بررسی علت تأخیر در ارزیابی‌ها.</p></div></div></div> }

function GoalDetail({ goal, close }: { goal: Goal; close: () => void }) { const [done, setDone] = useState([true, false, false]); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl md:p-8"><div className="flex items-start justify-between"><div><span className="text-xs font-semibold text-blue-600">جزئیات هدف · {goal.unit}</span><h2 className="mt-2 text-xl font-extrabold">{goal.title}</h2><p className="mt-1 text-sm text-slate-400">مسئول: {goal.owner}</p></div><button onClick={close} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={20} /></button></div><div className="mt-7 rounded-2xl bg-slate-50 p-5"><div className="flex items-end justify-between"><div><p className="text-xs text-slate-500">پیشرفت فعلی</p><p className="mt-1 text-4xl font-extrabold text-blue-600">{goal.actual}٪</p></div><StatusBadge status={goal.status} /></div><div className="mt-4 h-2 rounded-full bg-slate-200"><div className="h-full rounded-full bg-blue-600" style={{ width: `${goal.actual}%` }} /></div><div className="mt-3 flex justify-between text-[11px] text-slate-400"><span>هدف: {goal.plan}٪</span><span>اختلاف: {goal.actual - goal.plan}٪</span></div></div><div className="mt-7"><h3 className="font-bold">تاریخچه پیشرفت</h3><div className="mt-4 h-48"><ResponsiveContainer><LineChart data={[{ w: "هفته ۱", v: 20 }, { w: "هفته ۲", v: 30 }, { w: "هفته ۳", v: 42 }, { w: "هفته ۴", v: 50 }, { w: "هفته ۵", v: goal.actual }]}><CartesianGrid vertical={false} stroke="#eef2f7" /><XAxis dataKey="w" tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} tickFormatter={v => `${v}%`} tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip /><Line dataKey="v" stroke="#2563eb" strokeWidth={3} dot={{ r: 4 }} /></LineChart></ResponsiveContainer></div></div><div className="mt-6"><h3 className="font-bold">اقدامات بعدی</h3><div className="mt-3 space-y-2">{["تکمیل گزارش وضعیت فعلی", "برگزاری جلسه پیگیری با تیم", "ثبت برنامه جبرانی هفته آینده"].map((item, i) => <button key={item} onClick={() => setDone(d => d.map((x, j) => j === i ? !x : x))} className="flex w-full items-center gap-3 rounded-xl border border-slate-100 p-3 text-right text-sm text-slate-600 hover:bg-slate-50"><span className={`flex h-5 w-5 items-center justify-center rounded-md border ${done[i] ? "border-blue-600 bg-blue-600 text-white" : "border-slate-300"}`}>{done[i] && <Check size={13} />}</span><span className={done[i] ? "text-slate-400 line-through" : ""}>{item}</span></button>)}</div></div></div></div> }

function ReportModal({ close, submit, text, setText, progress, setProgress }: any) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><span className="text-xs font-semibold text-blue-600">هفته ۲۴ تا ۳۰ مرداد ۱۴۰۵</span><h2 className="mt-1 text-xl font-extrabold">ثبت گزارش هفتگی</h2></div><button type="button" onClick={close} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={20} /></button></div><label className="mt-6 block text-sm font-semibold">هدف موردنظر<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm"><option>برگزاری دوره‌های آموزشی</option><option>بهبود فرآیند ارزیابی عملکرد</option><option>راه‌اندازی داشبورد مدیریتی</option></select></label><label className="mt-4 block text-sm font-semibold">درصد تحقق این هفته<input type="number" value={progress} onChange={e => setProgress(e.target.value)} min="0" max="100" className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm" /></label><label className="mt-4 block text-sm font-semibold">دستاوردها، موانع و اقدامات آینده<textarea value={text} onChange={e => setText(e.target.value)} rows={5} placeholder="توضیحات گزارش را بنویسید..." className="mt-2 w-full resize-none rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm outline-none focus:border-blue-400" /></label><div className="mt-6 flex gap-2"><button type="submit" className="flex-1 rounded-xl bg-blue-600 py-3 text-sm font-bold text-white">ثبت گزارش</button><button type="button" onClick={close} className="rounded-xl border border-slate-200 px-5 text-sm font-semibold text-slate-600">انصراف</button></div></form></div> }

function GoalModal({ close, add }: any) { const [title, setTitle] = useState(""); const [owner, setOwner] = useState(""); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><form onSubmit={e => { e.preventDefault(); if (!title || !owner) return toast.error("عنوان و مسئول هدف الزامی است"); add({ title, owner, unit: "اجرایی", weight: 10, plan: 50, actual: 0, status: "انجام نشده", priority: "متوسط" }); }} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-xl font-extrabold">افزودن هدف جدید</h2><button type="button" onClick={close} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={20} /></button></div><label className="mt-6 block text-sm font-semibold">عنوان هدف<input value={title} onChange={e => setTitle(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-blue-400" placeholder="مثلاً: توسعه برنامه آموزشی" /></label><label className="mt-4 block text-sm font-semibold">مسئول هدف<input value={owner} onChange={e => setOwner(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-blue-400" placeholder="نام و نام خانوادگی" /></label><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-sm font-semibold">واحد<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-2 text-sm"><option>اجرایی</option><option>آموزش</option><option>نظارت</option></select></label><label className="text-sm font-semibold">اولویت<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-2 text-sm"><option>متوسط</option><option>بالا</option><option>کم</option></select></label></div><div className="mt-6 flex gap-2"><button className="flex-1 rounded-xl bg-blue-600 py-3 text-sm font-bold text-white">افزودن هدف</button><button type="button" onClick={close} className="rounded-xl border border-slate-200 px-5 text-sm font-semibold text-slate-600">انصراف</button></div></form></div> }
